Repository utm-cssc/website, pull requests merged in 2020-10, with the labels that each got.

#52 Categorized resources by tag
  components/global/ResourcesGrid.vue
  content/resources/android.md
  content/resources/collections.md
  content/resources/csc207.md
  content/resources/csc358.md
  content/resources/css.md
  content/resources/docker.md
  content/resources/html.md
  content/resources/javascript.md
  content/resources/mat102.md
  content/resources/mindset.md
  content/resources/podcasts.md
  content/resources/react-native.md
  content/resources/react.md
  content/resources/rest.md
  content/resources/resume.md
  content/resources/robotics.md
  content/resources/vue.md
  content/resources/web.md
  pages/resources/index.vue
Labels: Domain: User Experience, Role: Software Engineer, Type: Enhancement

#48 A component to display teammates
  .vscode/tasks.json
  components/global/Teammate.vue
  content/team/team.json
  pages/index.vue
  static/icons/email.svg
  static/icons/linkedin.svg
  static/team/lebron.jpg
Labels: Domain: User Experience, Priority: High, enhancement

#63 Added code quality fixing scripts
  .eslintignore
  .eslintrc
  .eslintrc.js
  .prettierignore
  .prettierrc
  nuxt.config.js
  package.json
  stylelint.config.js
  tailwind.config.js
  yarn.lock
Labels: Domain: Dev Experience, Role: Software Engineer, Type: Maintenance
