Repository utm-cssc/website, pull requests merged in 2020-11, with the labels that each got.

#58 Table of Contents Sidebar
  components/global/SideBar.vue
  pages/resources/_slug.vue
Labels: Domain: User Experience, Priority: Medium

#67 Added the glossary page
  components/global/FaqSearch.vue
  components/global/GlossaryHero.vue
  content/glossary.md
  content/resources/csc108.md
  content/resources/csc207.md
  content/resources/csc209.md
  content/resources/csc236.md
  nuxt.config.js
  package-lock.json
  package.json
  pages/glossary/index.vue
  plugins/vue-typed-js.js
  yarn.lock
Labels: Domain: User Experience, Role: Software Engineer, Type: Enhancement

#73 Add resource tag filter to resource categories
  layouts/default.vue
  pages/resources/index.vue
Labels: Domain: Organization, Domain: User Experience, enhancement
